import type { Metadata } from "next";
import { Noto_Sans } from "next/font/google";
import "./globals.css";
import Header from "@/components/header/header";
import Footer from "@/components/footer/footer";

const roboto = Noto_Sans({ subsets: ["vietnamese"], weight: ['100', '300']});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
  	children: React.ReactNode;
}>) {
  	return (
		<html lang="en">
		<body className={roboto.className}>
			{children}
		</body>
		</html>
  	);
}
